// Code generated by MockGen. DO NOT EDIT.
// Source: myinterface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMyInterface is a mock of MyInterface interface
type MockMyInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMyInterfaceMockRecorder
}

// MockMyInterfaceMockRecorder is the mock recorder for MockMyInterface
type MockMyInterfaceMockRecorder struct {
	mock *MockMyInterface
}

// NewMockMyInterface creates a new mock instance
func NewMockMyInterface(ctrl *gomock.Controller) *MockMyInterface {
	mock := &MockMyInterface{ctrl: ctrl}
	mock.recorder = &MockMyInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMyInterface) EXPECT() *MockMyInterfaceMockRecorder {
	return m.recorder
}

// DoStuff mocks base method
func (m *MockMyInterface) DoStuff() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DoStuff")
}

// DoStuff indicates an expected call of DoStuff
func (mr *MockMyInterfaceMockRecorder) DoStuff() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoStuff", reflect.TypeOf((*MockMyInterface)(nil).DoStuff))
}

// DoOtherStuf mocks base method
func (m *MockMyInterface) DoOtherStuf() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DoOtherStuf")
}

// DoOtherStuf indicates an expected call of DoOtherStuf
func (mr *MockMyInterfaceMockRecorder) DoOtherStuf() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoOtherStuf", reflect.TypeOf((*MockMyInterface)(nil).DoOtherStuf))
}
